### ISSUE TITLE
flagging DATE column

### ISSUE THREAD

**Issue by pshanmugathas** [derekbeaton/ONDRIApps#6] opened 2020-06-19 15:42 UTC
Hi Jed,

I'm currently working on the NIMG data package OND01_ALS_01_NIMG_FREESURFER_DESIKAN_2020MAY28

and there are multiple DATA and DICT files in this package, and when I check specifically the  OND01_ALS_01_NIMG_FREESURFER_DESIKAN_SUBCORTICAL_VOLUME_2020MAY28_DICT, I get the following message, but the DICT file does specify the DATE column as type DATE:

![image](https://user-images.githubusercontent.com/56092651/85151177-78e28f00-b221-11ea-81c9-09b5a9d0534c.png)

Would you be able to take a look?

Thank you,
Priya

**Comment by derekbeaton** [comment] 2020-06-22 15:17
Thanks! Assigning this to Roberto

**Comment by roblen001** [comment] 2020-06-22 17:22
@pshanmugathas @derekbeaton 

I believe I know what the issue is but I won't be able to access the data package to confirm my suspicion till the Lab Key maintenance is over. 

My hypothesis is that one of the column labels must have the word "DATE" within it, such as "UPDATE" and so the check expects it's type to be "DATE". Since the check looks for DATE in column labels.

**Comment by derekbeaton** [comment] 2020-06-22 17:31
I think @roblen001 is probably correct: this data package includes measures of the caudate.

@pshanmugathas if possible, could you quickly check to see if you get the same error, but please remove all the caudate variables?

if the error persists, it's something else. if it remains, we need to update the the way we find & check the date variable(s)

**Comment by ahnjedid** [comment] 2020-06-22 17:47
![ss](https://user-images.githubusercontent.com/22105889/85318551-2fe34280-b48e-11ea-9667-bd802465f5ce.png)

I added this comment in the GitLab repository (and presumably forgot about it), so @roblen001 is correct. For updated code, you can view the non-tabular check for column names at server/common/check/columnNames/checkDATAColumnNames.R

**Comment by pshanmugathas** [comment] 2020-06-22 17:55
> I think @roblen001 is probably correct: this data package includes measures of the caudate.
> 
> @pshanmugathas if possible, could you quickly check to see if you get the same error, but please remove all the caudate variables?
> 
> if the error persists, it's something else. if it remains, we need to update the the way we find & check the date variable(s)

**Comment by pshanmugathas** [comment] 2020-06-22 18:02
Thank you very much Roberto, Derek, and Jed for your help. 

Interestingly, I simply removed the 2 caudate variables (left and right caudate) and the error is gone?! 

![image](https://user-images.githubusercontent.com/56092651/85320393-fbbd5100-b490-11ea-97ed-b906434045e1.png)

**Comment by roblen001** [comment] 2020-06-22 18:44
@pshanmugathas np!  The issue was that when the program was checking the column names to see what should be considered a date type it was looking for a sub string called "date". Since "date" is a sub string of "caudate" it was expecting the column type to be "date".

Hopefully this explanation helps.

**Comment by roblen001** [comment] 2020-06-22 18:45
@derekbeaton Should i fix the code for date or all of the  other types too?

**Comment by pshanmugathas** [comment] 2020-06-22 18:47
Ohhh that makes sense!
Thank you Roberto!!

**Closed** 2020-07-15 18:41 UTC
